<%def name="render(x)">\
  NovaCompute${x}:
    Metadata:
      OpenStack::ImageBuilder::Elements:
      - nova-compute
      admin-password: unset
      glance:
        host:
          Fn::GetAtt:
          - notcompute
          - PrivateIp
      heat:
        access_key_id:
          Ref: Key
        refresh:
        - resource: NovaCompute
        secret_key:
          Fn::GetAtt:
          - Key
          - SecretAccessKey
        stack:
          name:
            Ref: AWS::StackName
          region:
            Ref: AWS::Region
      interfaces:
        control:
          Ref: NovaInterfaces
      keystone:
        host:
          Fn::GetAtt:
          - notcompute
          - PrivateIp
      neutron:
        host:
          Fn::GetAtt:
          - notcompute
          - PrivateIp
        ovs:
          bridge_mappings: ''
          enable_tunneling: 'True'
          local_ip: 0.0.0.0
          network_vlan_ranges: ''
          tenant_network_type: gre
        ovs_db:
          Fn::Join:
          - ''
          - - mysql://neutron:unset@
            - Fn::GetAtt:
              - notcompute
              - PrivateIp
            - /neutron
      nova:
        compute_driver:
          Ref: NovaComputeDriver
        db:
          Fn::Join:
          - ''
          - - mysql://nova:unset@
            - Fn::GetAtt:
              - notcompute
              - PrivateIp
            - /nova
        host:
          Fn::GetAtt:
          - notcompute
          - PrivateIp
      rabbit:
        host:
          Fn::GetAtt:
          - notcompute
          - PrivateIp
        password: guest
      service-password: unset
      swift:
        store_key: ''
        store_user: ''
    Properties:
      ImageId:
        Ref: NovaImage
      InstanceType:
        Ref: InstanceType
      KeyName:
        Ref: KeyName
    Type: AWS::EC2::Instance
</%def>\