<%namespace name="not_compute" file="not_compute.yaml"/>\
<%namespace name="compute" file="compute.yaml"/>\
<%namespace name="access_policy" file="access_policy.yaml"/>\
<% # Mapping between resource class service type and a HEAT template
   # TODO (mtaylor) Move this into Config file or add to model via API call.
   templates = {"compute": compute, "not_compute": not_compute, "controller": not_compute, "access_policy": access_policy} %>\
Description: Nova API,Keystone,Heat Engine and API,Glance,Neutron,Dedicated MySQL
  server,Dedicated RabbitMQ Server,Group of Nova Computes
HeatTemplateFormatVersion: '2012-12-12'
Parameters:
  AdminPassword:
    Default: unset
    Description: The password for the keystone admin account, used for monitoring,
      querying neutron etc.
    NoEcho: true
    Type: String
  AdminToken:
    Default: unset
    Description: The keystone auth secret.
    Type: String
  CinderPassword:
    Default: unset
    Description: The password for the cinder service account, used by cinder-api.
    NoEcho: true
    Type: String
  Flavor:
    Default: baremetal
    Description: Flavor to request when deploying.
    Type: String
  GlancePassword:
    Default: unset
    Description: The password for the glance service account, used by the glance services.
    NoEcho: true
    Type: String
  HeatPassword:
    Default: unset
    Description: The password for the Heat service account, used by the Heat services.
    NoEcho: true
    Type: String
  KeyName:
    Default: default
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: String
  NeutronPassword:
    Default: unset
    Description: The password for the neutron service account, used by neutron agents.
    NoEcho: true
    Type: String
  NovaComputeDriver:
    Default: libvirt.LibvirtDriver
    Type: String
  NovaComputeLibvirtType:
    Default: ''
    Type: String
  NovaImage:
    Default: overcloud-compute
    Type: String
  NovaInterfaces:
    Default: eth0
    Type: String
  NovaPassword:
    Default: unset
    Description: The password for the nova service account, used by nova-api.
    NoEcho: true
    Type: String
  PowerUserName:
    Default: stack
    Description: What username to ssh to the virtual power host with.
    Type: String
  notcomputeImage:
    Default: overcloud-control
    Type: String
Resources:
  AccessPolicy:
    Properties:
      AllowedResources:
      - notcompute
      - notcomputeConfig
    Type: OS::Heat::AccessPolicy
  ComputeAccessPolicy:
    Properties:
      AllowedResources:
<% for rc in resource_classes:
       if rc.service_type == "compute":
           for r in rc.racks:
               for n in r.nodes:
                   templates["access_policy"].render(n.node_id)
%>
    Type: OS::Heat::AccessPolicy
  ComputeKey:
    Properties:
      UserName:
        Ref: ComputeUser
    Type: AWS::IAM::AccessKey
  ComputeUser:
    Properties:
      Policies:
      - Ref: ComputeAccessPolicy
    Type: AWS::IAM::User
  Key:
    Properties:
      UserName:
        Ref: User
    Type: AWS::IAM::AccessKey
<% for rc in resource_classes:
       for r in rc.racks:
           for n in r.nodes:
               templates[rc.service_type].render(n.node_id)
%>
Outputs:
  KeystoneURL:
    Description: URL for the Overcloud Keystone service
    Value:
      Fn::Select:
        - 0
        - Fn::Select:
          - ctlplane
          - Fn::GetAtt:
            - notcompute
            - networks
