<%namespace name="not_compute" file="not_compute.yaml"/>\
<%namespace name="compute" file="compute.yaml"/>\
<% # Mapping between resource class service type and a HEAT template
   # TODO (mtaylor) Move this into Config file or add to model via API call.
   templates = {"compute": compute, "not_compute": not_compute, "controller": not_compute} %>\
Description: Nova API,Keystone,Heat Engine and API,Glance,Neutron,Dedicated MySQL
  server,Dedicated RabbitMQ Server,Group of Nova Computes
HeatTemplateFormatVersion: '2012-12-12'
Parameters:
  InstanceType:
    Default: baremetal
    Description: Flavor to request when deploying.
    Type: String
  KeyName:
    Default: default
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: String
  NovaComputeDriver:
    Default: libvirt.LibvirtDriver
    Type: String
  NovaImage:
    Default: overcloud-compute
    Type: String
  NovaInterfaces:
    Default: eth0
    Type: String
  PowerUserName:
    Default: stack
    Description: What username to ssh to the virtual power host with.
    Type: String
  notcomputeImage:
    Type: String
    Default: overcloud-control
Resources:
  AccessPolicy:
    Properties:
      AllowedResources:
      - notcompute
    Type: OS::Heat::AccessPolicy
  Key:
    Properties:
      UserName:
        Ref: User
    Type: AWS::IAM::AccessKey
  User:
    Properties:
      Policies:
      - Ref: AccessPolicy
    Type: AWS::IAM::User
<% for rc in resource_classes:
       for r in rc.racks:
           for n in r.nodes:
               templates[rc.service_type].render(n.node_id)
%>
Outputs:
  GlanceURL:
    Description: URL for the Overcloud Glance service
    Value:
      Fn::Join:
      - ''
      - - http://
        - Fn::GetAtt: [notcompute, PublicIp]
        - :9292/v1/
  HeatURL:
    Description: URL for the Overcloud Heat service
    Value:
      Fn::Join:
      - ''
      - - http://
        - Fn::GetAtt: [notcompute, PublicIp]
        - :8004/v1/
  KeystoneURL:
    Description: URL for the Overcloud Keystone service
    Value:
      Fn::Join:
      - ''
      - - http://
        - Fn::GetAtt: [notcompute, PublicIp]
        - :5000/v2.0/
  NovaURL:
    Description: URL for the Overcloud Nova service
    Value:
      Fn::Join:
      - ''
      - - http://
        - Fn::GetAtt: [notcompute, PublicIp]
        - :8774/v2/
  NeutronURL:
    Description: URL for the Overcloud Neutron service
    Value:
      Fn::Join:
      - ''
      - - http://
        - Fn::GetAtt: [notcompute, PublicIp]
        - :9696
